// <auto-generated />
using System;
using CI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260726143449_AddModifieManuellementFlag")]
    partial class AddModifieManuellementFlag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("CI.Models.Departement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Departements");
                });

            modelBuilder.Entity("CI.Models.Exports", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CibleFileUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateExport")
                        .HasColumnType("TEXT");

                    b.Property<int>("NbSugg")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceFileUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Exports");
                });

            modelBuilder.Entity("CI.Models.Scope", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Scopes");
                });

            modelBuilder.Entity("CI.Models.Suggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateMiseEnOeuvre")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateModificationManuelle")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateSuggestion")
                        .HasColumnType("date");

                    b.Property<int>("DepartementId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Economies")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("Kaizen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KaizenNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ModifieManuellement")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Mois")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeroSuggestion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Plant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ScopeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Situation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZoneLigne")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartementId");

                    b.HasIndex("NumeroSuggestion")
                        .IsUnique();

                    b.HasIndex("ScopeId");

                    b.ToTable("Suggestions");
                });

            modelBuilder.Entity("CI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CI.Models.Suggestion", b =>
                {
                    b.HasOne("CI.Models.Departement", "Departement")
                        .WithMany()
                        .HasForeignKey("DepartementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CI.Models.Scope", "Scope")
                        .WithMany()
                        .HasForeignKey("ScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departement");

                    b.Navigation("Scope");
                });
#pragma warning restore 612, 618
        }
    }
}
