// <auto-generated />
using System;
using CI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("CI.Models.Departement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Headcount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Departements");
                });

            modelBuilder.Entity("CI.Models.DepartementAnnualObjective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartementId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetPercent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DepartementId", "Year")
                        .IsUnique();

                    b.ToTable("DepartementAnnualObjectives");
                });

            modelBuilder.Entity("CI.Models.DepartementMonthlyObjective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartementId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mois")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetPercent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DepartementId", "Year", "Mois")
                        .IsUnique();

                    b.ToTable("DepartementMonthlyObjectives");
                });

            modelBuilder.Entity("CI.Models.DepartementScopeObjective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartementId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mois")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScopeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScopeId");

                    b.HasIndex("DepartementId", "ScopeId", "Year", "Mois")
                        .IsUnique();

                    b.ToTable("DepartementScopeObjectives");
                });

            modelBuilder.Entity("CI.Models.Exports", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CibleFileUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateExport")
                        .HasColumnType("TEXT");

                    b.Property<int>("NbSugg")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceFileUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Exports");
                });

            modelBuilder.Entity("CI.Models.Scope", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetPercent")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Scopes");
                });

            modelBuilder.Entity("CI.Models.StatutObjective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mois")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Statut", "Year", "Mois")
                        .IsUnique();

                    b.ToTable("StatutObjectives");
                });

            modelBuilder.Entity("CI.Models.Suggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateExportGlobal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateMiseEnOeuvre")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateModificationManuelle")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateSuggestion")
                        .HasColumnType("date");

                    b.Property<int>("DepartementId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Economies")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("ExporteVersGlobal")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Kaizen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KaizenNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ModifieManuellement")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Mois")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeroSuggestion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Plant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ScopeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Situation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceRowNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZoneLigne")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartementId");

                    b.HasIndex("NumeroSuggestion");

                    b.HasIndex("ScopeId");

                    b.HasIndex("SourceRowNo")
                        .IsUnique();

                    b.ToTable("Suggestions");
                });

            modelBuilder.Entity("CI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CI.Models.DepartementAnnualObjective", b =>
                {
                    b.HasOne("CI.Models.Departement", "Departement")
                        .WithMany()
                        .HasForeignKey("DepartementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departement");
                });

            modelBuilder.Entity("CI.Models.DepartementMonthlyObjective", b =>
                {
                    b.HasOne("CI.Models.Departement", "Departement")
                        .WithMany()
                        .HasForeignKey("DepartementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departement");
                });

            modelBuilder.Entity("CI.Models.DepartementScopeObjective", b =>
                {
                    b.HasOne("CI.Models.Departement", "Departement")
                        .WithMany()
                        .HasForeignKey("DepartementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CI.Models.Scope", "Scope")
                        .WithMany()
                        .HasForeignKey("ScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departement");

                    b.Navigation("Scope");
                });

            modelBuilder.Entity("CI.Models.Suggestion", b =>
                {
                    b.HasOne("CI.Models.Departement", "Departement")
                        .WithMany()
                        .HasForeignKey("DepartementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CI.Models.Scope", "Scope")
                        .WithMany()
                        .HasForeignKey("ScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departement");

                    b.Navigation("Scope");
                });
#pragma warning restore 612, 618
        }
    }
}
